config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  post '/listing/quandl' => 'welcome#listing_quandl_data', as: :listing_quandl_data

  post '/change_code_from_name' => 'welcome#change_code_from_name'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
## WelcomeController
require 'quandl'
class WelcomeController < ApplicationController
  include ActionView::Helpers::TextHelper
  def index
  end

  ## Listing Quandl Data in Tabluar Mode
  def listing_quandl_data
    Quandl::ApiConfig.api_key = ENV['quandl_api_key']
    Quandl::ApiConfig.api_version = ENV['quandl_api_version']
    begin
      @quandl_datas = Quandl::Database.get(params[:code]).datasets
    rescue => error
      @error = error
    end
  end

  def change_code_from_name
    if params[:name] == 'stocks'
      @codes = ['KFRENCH']
    elsif params[:name] == 'bonds'
      @codes = ['FED']
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quandl</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="header clearfix">
        <h3 class="text-muted">Quandl Demo</h3>
      </div>
      <%= yield %>
      <footer class="footer">
        <p>© 2015 TechCompose Solutions Pvt. Ltd.</p>
      </footer>
    </div>
  </body>
</html>

app/views/welcome/_change_code_from_name.html.erb
<%= select_tag 'code', options_for_select(@codes.collect{ |u| [u, u] }), class: 'form-control' %>

app/views/welcome/_listing_quandl_data.html.erb
<% if @quandl_datas.present? %>
  <table class='table'>
    <thead>
      <th>ID</th>
      <th>DATASET CODE</th>
      <th>NAME</th>
      <th>DESCRIPTION</th>
      <th>REFRESHED AT</th>
      <th>NEWEST AVAILABLE DATE</th>
      <th>OLDEST AVAILABLE DATE</th>
      <th>FREQUENCY</th>
      <th>TYPE</th>
      <th>PREMIUM</th>
      <th>DATABASE ID</th>
    </thead>
    <% @quandl_datas.values.each do |data| %>
      <tr>
        <td><%= data.id %></td>
        <td><%= data.dataset_code %></td>
        <td><%= data.name %></td>
        <td>
          <span title='<%= data.description %>'><%= truncate(data.description, escape: false) %></span>
        </td>
        <td><%= data.refreshed_at %></td>
        <td><%= data.newest_available_date %></td>
        <td><%= data.oldest_available_date %></td>
        <td><%= data.frequency %></td>
        <td><%= data.type %></td>
        <td><%= data.premium %></td>
        <td><%= data.database_id %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <%= @error.inspect %>
<% end %>

app/views/welcome/change_code_from_name.js.erb
$('.name_code').html("<%= escape_javascript(render :partial => '/welcome/change_code_from_name') %>")

app/views/welcome/index.html.erb
<%= form_tag listing_quandl_data_path, class: 'form-horizontal', method: 'post', remote: true do %>
  <div class="form-group">
    <label for="country" class="col-sm-2 control-label">Country</label>
    <div class="col-sm-10">USA</div>
  </div>
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">DATABASE</label>
    <div class="col-sm-10">
      <%= select_tag 'name', options_for_select([ ['STOCKS', 'stocks'], ['BONDS', 'bonds'] ]), class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">DATABASE CODE</label>
    <div class="col-sm-10 name_code">
      <%= select_tag 'code', options_for_select(['KFRENCH']), class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">&nbsp;</label>
    <div class="col-sm-10">
      <%= button_tag "Find Data", class: "btn btn-default submit-info", role: "button", data: { disable_with: "Please Wait...".html_safe} %>
    </div>
  </div>
<% end %>

<!-- Display Quandl Data -->
<hr>
<div id="quandl_data_info"></div>

app/views/welcome/listing_quandl_data.js.erb
$('#quandl_data_info').html("<%= escape_javascript(render :partial => '/welcome/listing_quandl_data') %>")